# Generated by Django 5.1.6 on 2025-02-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostmodel',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
